version: '3'
services:
  mongo:
    container_name: formio-mongodb
    image: mongo:4.1
    restart: always
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

  formio:
    container_name: formio-formio
    build: ./
    labels:
      com.wctsoft.formio.description: "汉化修改版formio"
      com.wctsoft.formio.mantainer: "caozhiwu <caozhiwu@wctsoft.com>"
    # The app will restart until Mongo is listening
    restart: always
    links:
      - mongo
    ports:
      - "3001:3001"
    environment:
      DEBUG: formio:*
      NODE_CONFIG: '{"mongo": "mongodb://root:admin@mongo:27017/formio?authSource=admin","host": "localhost:3001","domain": "localhost:3001"}'
      ROOT_EMAIL: 123@123.com
      ROOT_PASSWORD: 123
    stdin_open: true  # -i
    tty: true         # -t
